# ideally run gofumpt prior to any commit
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      # gofumpt
      - id: gofumpt
        name: Run formatter (gofumpt)
        entry: gofumpt
        language: "system"
        exclude: "(^|/)vendor/"
        types: [go]
